@generated
{
  "kind": "model",
  "data": {
    "callable": "_test_sink",
    "filename": "builtins.pyi",
    "callable_line": 618,
    "sinks": [
      {
        "port": "formal(arg, position=0)",
        "taint": [
          {
            "kinds": [
              {
                "features": [ { "always-via": "special_sink" } ],
                "kind": "Test"
              }
            ],
            "declaration": null
          }
        ]
      }
    ],
    "modes": [ "Obscure" ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "_test_source",
    "filename": "builtins.pyi",
    "callable_line": 619,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "features": [ { "always-via": "special_source" } ],
                "kind": "Test"
              }
            ],
            "declaration": null
          }
        ]
      }
    ],
    "modes": [ "Obscure" ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.none_throws",
    "filename": "exception_test.py",
    "callable_line": 25,
    "tito": [
      {
        "port": "formal(x, position=0)",
        "taint": [
          {
            "kinds": [ { "return_paths": { "": 4 }, "kind": "LocalReturn" } ],
            "tito": {}
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_before_try_to_finally",
    "filename": "exception_test.py",
    "callable_line": 38,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "local_features": [ { "always-via": "tito" } ],
            "tito_positions": [ { "line": 41, "start": 27, "end": 28 } ],
            "origin": { "line": 39, "start": 8, "end": 22 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "issue",
  "data": {
    "callable": "exception_test.test_before_try_to_finally",
    "callable_line": 38,
    "code": 5002,
    "line": 43,
    "start": 19,
    "end": 20,
    "filename": "exception_test.py",
    "message": "Data from [Test] source(s) may reach [Test] sink(s)",
    "traces": [
      {
        "name": "forward",
        "roots": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 39, "start": 8, "end": 22 }
          }
        ]
      },
      {
        "name": "backward",
        "roots": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_sink" } ],
                "leaves": [ { "name": "_test_sink", "port": "leaf:arg" } ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 43, "start": 19, "end": 20 },
            "call_site": "43:8-43:21"
          }
        ]
      }
    ],
    "features": [
      { "always-via": "special_source" }, { "always-via": "special_sink" }
    ],
    "sink_handle": {
      "kind": "Call",
      "callee": "_test_sink",
      "index": 0,
      "parameter": "formal(arg)"
    },
    "master_handle": "exception_test.test_before_try_to_finally:5002:0:Call|_test_sink|0|formal(arg):592321a59534b02a2dab5f619e054218"
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_caught_exception",
    "filename": "exception_test.py",
    "callable_line": 18,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "leaves": [
                  { "name": "BaseException.__str__", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 22, "start": 15, "end": 22 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_constructed_exception",
    "filename": "exception_test.py",
    "callable_line": 13,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "leaves": [
                  { "name": "BaseException.__init__", "port": "leaf:self" }
                ],
                "kind": "Test"
              }
            ],
            "local_features": [
              { "always-via": "obscure:model" }, { "always-via": "tito" }
            ],
            "tito_positions": [ { "line": 15, "start": 15, "end": 17 } ],
            "origin": { "line": 14, "start": 9, "end": 18 },
            "call_site": "14:9-14:29"
          },
          {
            "kinds": [
              {
                "leaves": [
                  { "name": "BaseException.__str__", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 15, "start": 11, "end": 18 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "issue",
  "data": {
    "callable": "exception_test.test_except_to_finally",
    "callable_line": 56,
    "code": 5002,
    "line": 63,
    "start": 19,
    "end": 20,
    "filename": "exception_test.py",
    "message": "Data from [Test] source(s) may reach [Test] sink(s)",
    "traces": [
      {
        "name": "forward",
        "roots": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 61, "start": 12, "end": 26 }
          }
        ]
      },
      {
        "name": "backward",
        "roots": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_sink" } ],
                "leaves": [ { "name": "_test_sink", "port": "leaf:arg" } ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 63, "start": 19, "end": 20 },
            "call_site": "63:8-63:21"
          }
        ]
      }
    ],
    "features": [
      { "always-via": "special_source" }, { "always-via": "special_sink" }
    ],
    "sink_handle": {
      "kind": "Call",
      "callee": "_test_sink",
      "index": 0,
      "parameter": "formal(arg)"
    },
    "master_handle": "exception_test.test_except_to_finally:5002:0:Call|_test_sink|0|formal(arg):847a13df579e034004a8fdef4fc1f9a7"
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_parameter_flow",
    "filename": "exception_test.py",
    "callable_line": 9,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "leaves": [
                  { "name": "BaseException.__str__", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 10, "start": 11, "end": 18 }
          }
        ]
      }
    ],
    "tito": [
      {
        "port": "formal(ex, position=0)",
        "taint": [
          {
            "kinds": [
              {
                "return_paths": { "": 0 },
                "length": 1,
                "kind": "LocalReturn"
              }
            ],
            "local_features": [
              { "always-via": "obscure:model" }, { "always-via": "tito" }
            ],
            "tito_positions": [ { "line": 10, "start": 15, "end": 17 } ],
            "tito": {}
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_return_finally",
    "filename": "exception_test.py",
    "callable_line": 66,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 70, "start": 15, "end": 29 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_return_overrides_finally",
    "filename": "exception_test.py",
    "callable_line": 80,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 84, "start": 15, "end": 29 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_return_twice_finally",
    "filename": "exception_test.py",
    "callable_line": 73,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 77, "start": 15, "end": 29 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_sink_in_finally",
    "filename": "exception_test.py",
    "callable_line": 31,
    "sinks": [
      {
        "port": "formal(x, position=0)",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_sink" } ],
                "leaves": [ { "name": "_test_sink", "port": "leaf:arg" } ],
                "kind": "Test"
              }
            ],
            "origin": { "line": 35, "start": 19, "end": 20 },
            "call_site": "35:8-35:21"
          }
        ]
      }
    ],
    "tito": [
      {
        "port": "formal(x, position=0)",
        "taint": [
          {
            "kinds": [
              {
                "return_paths": { "": 4 },
                "length": 1,
                "kind": "LocalReturn"
              }
            ],
            "local_features": [ { "always-via": "tito" } ],
            "tito_positions": [ { "line": 33, "start": 27, "end": 28 } ],
            "tito": {}
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_within_try_to_finally",
    "filename": "exception_test.py",
    "callable_line": 46,
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "kinds": [
              {
                "local_features": [ { "always-via": "special_source" } ],
                "leaves": [
                  { "name": "_test_source", "port": "leaf:return" }
                ],
                "kind": "Test"
              }
            ],
            "local_features": [ { "always-via": "tito" } ],
            "tito_positions": [ { "line": 50, "start": 27, "end": 28 } ],
            "origin": { "line": 49, "start": 12, "end": 26 }
          }
        ]
      }
    ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "BaseException.__init__",
    "filename": "builtins.pyi",
    "callable_line": 60,
    "sources": [
      {
        "port": "formal(self, position=0)",
        "taint": [ { "kinds": [ { "kind": "Test" } ], "declaration": null } ]
      }
    ],
    "modes": [ "Obscure" ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "BaseException.__repr__",
    "filename": "builtins.pyi",
    "callable_line": 62,
    "sources": [
      {
        "port": "result",
        "taint": [ { "kinds": [ { "kind": "Test" } ], "declaration": null } ]
      }
    ],
    "modes": [ "Obscure" ]
  }
}
{
  "kind": "model",
  "data": {
    "callable": "BaseException.__str__",
    "filename": "builtins.pyi",
    "callable_line": 61,
    "sources": [
      {
        "port": "result",
        "taint": [ { "kinds": [ { "kind": "Test" } ], "declaration": null } ]
      }
    ],
    "modes": [ "Obscure" ]
  }
}
